language: python
python: 2.7
env:
# for when fabric updates
#  - TOX_ENV=py34
#  - TOX_ENV=py33
  - TOX_ENV=py27
install:
  - pip install tox
  - pip install python-coveralls
script:
  - tox -e $TOX_ENV
after_success:
  coveralls