language: python
python:
  - 2.7
  - 3.5
env:
# for when fabric updates
#  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=py27
install:
  - pip install tox
  - pip install python-coveralls
script:
  - tox -e $TOX_ENV
after_success:
  coveralls
